name: tokbusarrival
description: A SG Bus Arrivial Annoucement App with Text to Speech, Speech to Text and Computer Vision.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  meta_bus_arrivals_api:
    path: packages/meta_bus_arrivals_api #using own unpublished package
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  hydrated_bloc: ^7.0.1
  intl: ^0.17.0
  flutter_tts: ^3.2.2
  path_provider: ^2.0.2
  google_ml_kit: ^0.7.2
  camera: ^0.9.4+3
  speech_to_text: ^5.1.1
  flutter_svg: ^0.22.0
  bus_stops:
    path: packages/bus_stops #using own unpublished package for the stop model
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path: ^1.8.0
  package_info_plus: ^1.3.0
  geolocator: ^7.6.2
  kdtree: ^0.2.0
  google_fonts: ^2.1.0
  vibration: ^1.7.4-nullsafety.0
  shared_preferences: ^2.0.8
  in_app_review: ^2.0.3
  flutter_map: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  bloc_test: ^8.2.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.4

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/ic_bus.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bus_pole_sample.png
    - assets/images/doubledeck.svg
    - assets/images/singledeck.svg
    - assets/images/lovebus.png
    - assets/images/ic_launcher.png
    - assets/files/bus_stop.json
    - assets/files/bus_stop_meta.json
    - assets/images/nothing_to_see.png
    - assets/images/nothing_to_see_cloud.png
    - assets/images/bus_stop.png
    - assets/images/car.png
    - assets/images/bus_timer_indicator.png
    - assets/images/bus_stop_marker.png
    - assets/google_fonts/
    # tutorials related files
    - assets/tutorials/images/feature_find.png
    - assets/tutorials/images/feature_hear.png
    - assets/tutorials/images/feature_scan.png
    - assets/tutorials/images/feature_speak.png
    - assets/tutorials/images/feature_timer.png
    - assets/tutorials/images/feature_map.png
    - assets/tutorials/images/feature_bookmark.png
    - assets/tutorials/captions/feature_find.txt
    - assets/tutorials/captions/feature_hear.txt
    - assets/tutorials/captions/feature_scan.txt
    - assets/tutorials/captions/feature_speak.txt
    - assets/tutorials/captions/feature_timer.txt
    - assets/tutorials/captions/feature_map.txt
    - assets/tutorials/captions/feature_bookmark.txt
    - assets/tutorials/contents/feature_find.txt
    - assets/tutorials/contents/feature_hear.txt
    - assets/tutorials/contents/feature_scan.txt
    - assets/tutorials/contents/feature_speak.txt
    - assets/tutorials/contents/feature_timer.txt
    - assets/tutorials/contents/feature_map.txt
    - assets/tutorials/contents/feature_bookmark.txt
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  